# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88945580029f4242b92d94a917cfd033c43a119b371b246b3df3872169d305926d7b3d332700309d5532c51321354dfc12a5009647f2428d980819e1d0f4debd

test:
  secret_key_base: a900e17157086710583e49e7c6035ef0239975efcb1f4b047cfce466d062242da2365bae49e4f88764193352aa0aeb8f32f5286a7fc2e23e479b1889033092ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
